"""bulla: Witness kernel for agent tool compositions — diagnose, attest, seal."""

__version__ = "0.31.0"

from bulla.model import (
    BlindSpot,
    BoundaryObligation,
    Bridge,
    BridgePatch,
    Composition,
    ContradictionReport,
    ContradictionSeverity,
    DEFAULT_POLICY_PROFILE,
    Diagnostic,
    Disposition,
    Edge,
    ObligationVerdict,
    PackRef,
    PolicyProfile,
    ProbeResult,
    SemanticDimension,
    ToolSpec,
    WitnessBasis,
    WitnessError,
    WitnessErrorCode,
    WitnessReceipt,
)
from bulla.diagnostic import (
    ConditionalDiagnostic,
    FeeDecomposition,
    OpenPort,
    Resolution,
    boundary_obligations_from_decomposition,
    check_obligations,
    conditional_diagnose,
    decompose_fee,
    diagnose,
    minimum_disclosure_set,
    prescriptive_disclosure,
    resolve_conditional,
    satisfies_obligations,
)
from bulla.repair import (
    ConvergenceResult,
    RepairResult,
    coordination_step,
    detect_contradictions,
    detect_contradictions_across,
    detect_expected_value_contradictions,
    extract_pack_from_probes,
    repair_composition,
    repair_step,
)
from bulla.parser import load_composition
from bulla.guard import BullaGuard, BullaCheckError
from bulla.witness import (
    verify_receipt_consistency,
    verify_receipt_integrity,
    witness,
)
from bulla.infer.classifier import FieldInfo, InferredDimension
from bulla.config import ConfigError, McpServerEntry, find_mcp_config, parse_mcp_config
from bulla.scan import ServerScanResult, scan_mcp_servers_parallel

__all__ = [
    "__version__",
    "BlindSpot",
    "Bridge",
    "BridgePatch",
    "BullaCheckError",
    "BoundaryObligation",
    "ContradictionReport",
    "ContradictionSeverity",
    "ConvergenceResult",
    "BullaGuard",
    "Composition",
    "ConditionalDiagnostic",
    "DEFAULT_POLICY_PROFILE",
    "Diagnostic",
    "Disposition",
    "FeeDecomposition",
    "Edge",
    "FieldInfo",
    "InferredDimension",
    "PackRef",
    "PolicyProfile",
    "SemanticDimension",
    "ToolSpec",
    "WitnessBasis",
    "WitnessError",
    "WitnessErrorCode",
    "ObligationVerdict",
    "OpenPort",
    "ProbeResult",
    "RepairResult",
    "Resolution",
    "WitnessReceipt",
    "boundary_obligations_from_decomposition",
    "check_obligations",
    "conditional_diagnose",
    "coordination_step",
    "decompose_fee",
    "detect_contradictions",
    "detect_contradictions_across",
    "detect_expected_value_contradictions",
    "diagnose",
    "extract_pack_from_probes",
    "minimum_disclosure_set",
    "prescriptive_disclosure",
    "repair_composition",
    "repair_step",
    "resolve_conditional",
    "satisfies_obligations",
    "load_composition",
    "verify_receipt_consistency",
    "verify_receipt_integrity",
    "witness",
    "ConfigError",
    "McpServerEntry",
    "ServerScanResult",
    "find_mcp_config",
    "parse_mcp_config",
    "scan_mcp_servers_parallel",
]
