import InterpolantEnvelope.Finite
import InterpolantEnvelope.Refinement
import InterpolantEnvelope.Settlement
import InterpolantEnvelope.Golden
import InterpolantEnvelope.GoldenV02
import InterpolantEnvelope.Boundary
import InterpolantEnvelope.ClaimFlow
import InterpolantEnvelope.Generalization
import InterpolantEnvelope.AssuranceLinker

open InterpolantEnvelope

#print axioms checked_interpolant_defines
#print axioms two_copy_interpolant_defines
#print axioms two_expansions_rule_out_explicit_definition
#print axioms rely_surface_sound
#print axioms refusal_surface_sound
#print axioms sound_envelope_never_relies_and_refuses
#print axioms full_package_safe
#print axioms sameChoiceClass_refl
#print axioms sameChoiceClass_symm
#print axioms sameChoiceClass_trans
#print axioms same_class_selection_preserves_definition
#print axioms inequivalent_minima_are_distinct_choice_classes
#print axioms determines_iff_separates_opposing_pairs
#print axioms definitelyPositive_monotone
#print axioms definitelyNegative_monotone
#print axioms ambiguity_antitone
#print axioms envelope_refinement_sound
#print axioms admitted_constraint_refines
#print axioms preserve_is_refinement
#print axioms refinement_never_changes_epoch
#print axioms InterpolantEnvelope.Settlement.step_is_honest
#print axioms InterpolantEnvelope.Settlement.answerable_ratchet_trace
#print axioms InterpolantEnvelope.Settlement.conflict_non_mutation
#print axioms InterpolantEnvelope.Settlement.refinement_monotone_between_revisions
#print axioms InterpolantEnvelope.Settlement.ambiguity_reserve_antitone_under_refinement
#print axioms InterpolantEnvelope.Golden.full_minterm_fallback_sound
#print axioms InterpolantEnvelope.Golden.anytime_positive_monotone
#print axioms InterpolantEnvelope.Golden.anytime_negative_monotone
#print axioms InterpolantEnvelope.Golden.anytime_residual_antitone
#print axioms InterpolantEnvelope.Golden.anytime_refines_trans
#print axioms InterpolantEnvelope.Golden.verified_plan_sufficient_without_minimality
#print axioms InterpolantEnvelope.Golden.neighborhood_change_requires_new_epoch
#print axioms InterpolantEnvelope.Golden.reserve_antitone_fixed_neighborhood
#print axioms InterpolantEnvelope.GoldenV02.literal_dropping_sound
#print axioms InterpolantEnvelope.GoldenV02.sufficient_cube_cover_sound
#print axioms InterpolantEnvelope.GoldenV02.truncation_preserves_safety
#print axioms InterpolantEnvelope.GoldenV02.truncated_regions_disjoint
#print axioms InterpolantEnvelope.Boundary.entailment_does_not_manufacture_ground
#print axioms InterpolantEnvelope.Boundary.grounding_determined_iff_all_opposing_pairs_separated
#print axioms InterpolantEnvelope.Boundary.mixed_observation_class_blocks_total_decision
#print axioms InterpolantEnvelope.Boundary.trace_refinement_preserves_decided_surfaces
#print axioms InterpolantEnvelope.Boundary.trace_refinement_trans
#print axioms InterpolantEnvelope.ClaimFlow.no_borrowed_authority
#print axioms InterpolantEnvelope.ClaimFlow.no_free_precedent
#print axioms InterpolantEnvelope.ClaimFlow.case_only_finding_cannot_derive_general_precedent
#print axioms InterpolantEnvelope.ClaimFlow.binding_precedent_only_inside_declared_reason_and_scope
#print axioms InterpolantEnvelope.ClaimFlow.same_epoch_precedent_refinement_preserves_surfaces
#print axioms InterpolantEnvelope.ClaimFlow.supersession_preserves_historical_decision
#print axioms InterpolantEnvelope.ClaimFlow.increasing_budget_does_not_change_semantic_epoch
#print axioms InterpolantEnvelope.ClaimFlow.verified_trace_append
#print axioms InterpolantEnvelope.AssuranceLinker.claim_non_amplification
#print axioms InterpolantEnvelope.AssuranceLinker.guarantee_separation
#print axioms InterpolantEnvelope.AssuranceLinker.capital_conservation
#print axioms InterpolantEnvelope.AssuranceLinker.settlement_soundness
#print axioms InterpolantEnvelope.AssuranceLinker.withholding_monotonicity
#print axioms InterpolantEnvelope.AssuranceLinker.rail_invariance
#print axioms InterpolantEnvelope.AssuranceLinker.correction_non_erasure
#print axioms InterpolantEnvelope.AssuranceLinker.semantic_epoch_safety
#print axioms InterpolantEnvelope.AssuranceLinker.authority_epoch_safety
#print axioms InterpolantEnvelope.AssuranceLinker.mismatch_conformance_exclusion
#print axioms InterpolantEnvelope.AssuranceLinker.digest_relation_total
#print axioms InterpolantEnvelope.AssuranceLinker.witnessed_recourse_soundness
#print axioms InterpolantEnvelope.AssuranceLinker.open_challenge_blocks_remedy
#print axioms InterpolantEnvelope.AssuranceLinker.early_expiry_blocks_remedy
#print axioms InterpolantEnvelope.AssuranceLinker.unordered_history_blocks_remedy
#print axioms InterpolantEnvelope.AssuranceLinker.appraisal_cannot_auto_remedy
#print axioms InterpolantEnvelope.AssuranceLinker.semantic_cannot_auto_remedy
#print axioms InterpolantEnvelope.AssuranceLinker.consistent_history_equivocation_exclusion
#print axioms InterpolantEnvelope.AssuranceLinker.one_view_cannot_establish_equivocation
#print axioms InterpolantEnvelope.AssuranceLinker.witness_remedy_eligibility_soundness
#print axioms InterpolantEnvelope.AssuranceLinker.witness_remedy_soundness
#print axioms InterpolantEnvelope.AssuranceLinker.witness_open_challenge_blocks_remedy
#print axioms InterpolantEnvelope.AssuranceLinker.missing_witness_bond_blocks_remedy
#print axioms InterpolantEnvelope.AssuranceLinker.model_identity_cannot_auto_witness_remedy
#print axioms InterpolantEnvelope.AssuranceLinker.witness_bond_separation
#print axioms InterpolantEnvelope.AssuranceLinker.witness_withholding_cannot_improve_fault
#print axioms InterpolantEnvelope.AssuranceLinker.attempt_report_separation
#print axioms InterpolantEnvelope.AssuranceLinker.declared_path_from_witness_fault_requires_recheck
#print axioms InterpolantEnvelope.AssuranceLinker.incomplete_lineage_cannot_clear
#print axioms InterpolantEnvelope.AssuranceLinker.complete_unrelated_branch_remains_unaffected
#print axioms InterpolantEnvelope.AssuranceLinker.witness_fault_does_not_strengthen_substantive_claim
#print axioms InterpolantEnvelope.Generalization.candidate_cannot_mutate_semantic_state
#print axioms InterpolantEnvelope.Generalization.adoption_and_applicability_are_separate_premises
#print axioms InterpolantEnvelope.Generalization.safe_scopes_downward_closed
#print axioms InterpolantEnvelope.Generalization.unsafe_witness_invalidates_every_containing_superscope
#print axioms InterpolantEnvelope.Generalization.widening_cannot_reduce_represented_yield
#print axioms InterpolantEnvelope.Generalization.increased_budget_cannot_reverse_certified_cell
#print axioms InterpolantEnvelope.Generalization.categorical_effect_barrier_survives_disguise
#print axioms InterpolantEnvelope.Generalization.supersession_preserves_history_without_automatic_future_governance
